import './globals.css';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { getUserBySessionToken } from '../database/users';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default async function RootLayout({ children }) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');

  const user = !sessionToken?.value
    ? undefined
    : await getUserBySessionToken(sessionToken.value);

  return (
    <html lang="en">
      <head />
      <body className="mb-4 p-2">
        <div className="navbar">
          <div className="flex-1 px-2 lg:flex-none" />
          <div className="flex justify-end flex-2 px-0">
            <div className="flex items-stretch">
              <div className="dropdown dropdown-end">
                <label tabIndex={0} className="btn btn-ghost rounded-btn">
                  MENU
                </label>
                <ul className="menu dropdown-content p-2 shadow bg-beige rounded-box w-52 mt-4">
                  <li>
                    <a href="/">HOME</a>
                  </li>

                  <li>
                    <a href="/events">EVENTS</a>
                  </li>
                  <li>
                    {' '}
                    <Link href="/login">LOGIN</Link>
                  </li>
                  <li>
                    {' '}
                    <Link href="/register">REGISTER</Link>
                  </li>
                  <li>
                    <Link href="/logout" prefetch={false}>
                      LOGOUT{' '}
                    </Link>
                  </li>
                  <li>
                    <Link href={`/profile/${user && user.username}`}>
                      Nice to see you, {user && user.username}
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
