import './globals.css';
import Link from 'next/link';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <nav>
          <div>
            <Link href="/">Home</Link>
            <Link href="/events">Events</Link>
            <Link href="/create">Create</Link>
            <Link href="/profile">Profile</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
